import Link from "next/link";
import { ArrowLeft } from "lucide-react";

import SubscribeForm from "@/components/subscribe-form/SubscribeForm";

export default function AboutPage() {
  return (
    <main className="space-y-8">
      <header className="space-y-2">
        <p className="text-xs font-semibold uppercase tracking-widest text-indigo-600 dark:text-indigo-400">
          About
        </p>
        <h1 className="text-3xl font-bold tracking-tight text-slate-900 dark:text-white">About</h1>
        <p className="text-sm text-slate-600 dark:text-slate-400">
          This is a Next.js App Router baseline generated by the nextjs-stack-pack bootstrapper.
        </p>
      </header>
      <div className="rounded-2xl border border-slate-200/70 bg-white/80 p-6 shadow-sm backdrop-blur dark:border-slate-800 dark:bg-slate-900/60">
        <SubscribeForm />
      </div>
      <Link
        href="/"
        className="inline-flex items-center gap-1.5 text-sm font-medium text-indigo-600 transition-colors hover:text-indigo-700 dark:text-indigo-400 dark:hover:text-indigo-300"
      >
        <ArrowLeft className="h-4 w-4" aria-hidden="true" />
        Back home
      </Link>
    </main>
  );
}
